variables:
  S3_BUCKET_NAME: "dashboard.flopay.io"

deploy to production:
  environment: production
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp dist/ s3://$S3_BUCKET_NAME/ --recursive --include "*" --exclude ".gitlab-ci.yml" --exclude "*.git*" --exclude "*.sass-cache*" --include "*.html" --include "*.js" "static/js/*"
  only:
  - master

pages:
  image: alpine:latest
  environment: staging
  script:
  - mkdir -p ./public
  - cp ./*.html ./public/
  artifacts:
    paths:
    - public
  except:
  - master
