image: node:latest

variables:
  S3_BUCKET_NAME: "dashboard.flopay.io"

stages:
  - build
  - deploy

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    #    expire_in: 1h
    paths:
      - dist

deploy to production:
  stage: deploy
  environment: production
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp dist/ s3://$S3_BUCKET_NAME/ --recursive  --include "*.html"
  only:
  - master

pages:
  stage: deploy
  image: alpine:latest
  environment: staging
  script:
  - mkdir -p ./public
  - cp ./*.html ./public/
  artifacts:
    paths:
    - public
  except:
  - master
